Fix gcc tools wrapper for 32-bit archs
The gcc-sdk/* wrappers default on 64-bit tools if neither -m32 nor -m64
is passed. As ar doesn't understand either of these there is no way to
tell it to use the 32-bit variant.

This change defaults on 64-bit tools if the host appears to be
64-bit-ish, 32-bit tools otherwise.

Also fixes a few other stylistic things (error messages go to stderr,
use exec at the end, fix typo in error message).

Change-Id: Ie41aa1716baf247c90ce6952afac37927652fb90

diff --git a/gcc-sdk/gcc b/gcc-sdk/gcc
--- a/gcc-sdk/gcc
+++ b/gcc-sdk/gcc
@@ -2,9 +2,17 @@
 
 HOST_OS=`uname -s | tr '[:upper:]' '[:lower:]'`
 if [ "$HOST_OS" != "linux" ] ; then
-  echo "ERROR: The gcc this script points to can only run on linux"
+  echo "ERROR: The gcc this script points to can only run on linux" >&2
   exit 1
 fi
+
+
+# determine if host is running 64-bit OS.
+# Note that "uname -m" only show host CPU is capable of.  Use the following technique
+# from ndk/build/core/ndk-common.sh instead
+is_64bit() {
+  file -L "$SHELL" | grep -q "x86[_-]64" && return 0 || return 1
+}
 
 PROGNAME=`basename $0`
 
@@ -20,21 +28,29 @@ suffix_m64=${options##* -m64 }    # suffix after the last -m64
 len_m32=${#suffix_m32}            # length of suffix after the last -m32
 len_m64=${#suffix_m64}            # length of suffix after the last -m64
 
-if [ $len_m32 -ge $len_m64 ] ; then
-  # Choose 64-bit if -m64 only, -m64 appears after -m32, or neither exist (-eq)
+# check for -m32/-m64
+if [ $len_m32 -gt $len_m64 ]; then
+    # -m64 after -m32
+    use_64=1
+elif [ $len_m64 -gt $len_m32 ]; then
+    # -m32 after -m64
+    use_64=0
+elif is_64bit; then
+    # neither -m32 nor -m64 passed, choose whether to use
+    # 32 or 64 bit based on host arch
+    use_64=1
+else
+    use_64=0
+fi
+
+if [ $use_64 -eq 1 ]; then
   MY_TOOL=`dirname $0`/${PREFIX64}-${PROGNAME}
-  # Make sure host is running 64-bit OS.
-  # Note that "uname -m" only show host CPU is capable of.  Use the following technique
-  # from ndk/build/core/ndk-common.sh instead
-  file -L "$SHELL" | grep -q "x86[_-]64"
-  if [ $? != 0 ]; then
-    # $SHELL is not a 64-bit executable, so assume our userland is too.
-    echo "ERROR: $MY_TOOL only run on 64-bit linux"
+  if ! is_64bit; then
+    echo "ERROR: $MY_TOOL only runs on 64-bit linux" >&2
     exit 1
   fi
 else
-  # Otherwise, choose 32-bit
   MY_TOOL=`dirname $0`/${PREFIX32}-${PROGNAME}
 fi
 
-$MY_TOOL "$@"
+exec $MY_TOOL "$@"
